name: CD
on:
  push:
    branches:
      - develop

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.2

      - name: Install sponge
        run: sudo apt-get install moreutils

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.ref_name }}

      - run: npm ci

      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3

      - name: Release
        if: success()
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx run-many --target release --all
