name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}

      - run: npm ci

      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
