name: Release
on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: Select package to publish
        options:
          - nestjs-auth
          - nestjs-logger
          - storage
jobs:
  dev_to_master:
    name: merge dev into master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Merge branch
        uses: emiliopedrollo/auto-merge@v1.2.0
        if: github.ref_name == 'master'
        with:
          github_token: ${{ github.token }}
          source_ref: develop
          target_branch: master
          allow_fast_forward: false
  build_package:
    name: build package
    needs:
      - dev_to_master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set NX sha
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.ref_name }}
      - name: NPM clean install
        run: npm ci
      - run: npx nx workspace-lint
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
      - name: Release
        if: success()
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx run ${{ inputs.package }}:release
  master_to_dev:
    name: merge master into dev
    needs:
      - dev_to_master
      - build_package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Merge branch
        uses: emiliopedrollo/auto-merge@v1.2.0
        with:
          github_token: ${{ github.token }}
          source_ref: master
          target_branch: develop
          allow_fast_forward: false
