name: Release
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'

      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check --verbose
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx build auth

      - name: Release
        if: success()
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx affected --target release --all
          npx semantic-release-plus
